namespace: aap
schedule: "0 0 * * 0" # every sunday at midnight
backupFilenamePrefix: export-results
# GitHub Configuration
githubSecretName: "github-credentials" # Secret containing username and password keys
githubRepoUrl: "https://github.com/yakovbeder/aap.git" # UPDATE THIS with your GitHub repo URL
# Controller Configuration
controllerHost: "https://aap-controller-aap.apps.yb-ocp4.rh-igc.com"
controllerUsername: "admin"
controllerAdminSecretName: "aap-controller-admin-password"
