---
# Array of AAP Inventory definitions
controller_inventories:
  - name: "Developers Inventory"
    organization: "Default"
    description: "A sample inventory for developers"

  - name: "Production Web Servers"
    organization: "Default"
    description: "Inventory for all production web servers"

